version: '3.7'

services:
  db:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_DB: prisma
      POSTGRES_PASSWORD: prisma
    ports:
      - '5432:5432'
    container_name: prisma
    volumes:
      - ./src/prisma/tmp/postgres:/var/lib/postgresql/data
